name: Build and Deploy Academy Backend to Azure VM (DEV)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            uriteam/urisvc:academybackenddev-${{ github.sha }}
            uriteam/urisvc:academybackenddev

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Copy docker-compose.yml to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: urifusion
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/tmp/"
          strip_components: 0

      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_IP }}
          username: urifusion
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su - uritest -c "
            if [ ! -d /home/uritest/academy-backend ]; then
              mkdir -p /home/uritest/academy-backend;
            fi
            cd /home/uritest/academy-backend
            "
            sudo cp /tmp/docker-compose.yml /home/uritest/academy-backend/docker-compose.yml
            sudo chown uritest:uritest /home/uritest/academy-backend/docker-compose.yml
            sudo su - uritest -c "
            cd /home/uritest/academy-backend
            echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
            
            # Stop and remove the specific container to ensure clean restart
            docker-compose stop academy-backend.api
            docker-compose rm -f academy-backend.api

            # Remove old image to force pull of new one
            docker rmi uriteam/urisvc:academybackenddev || true

            docker-compose pull
            docker-compose up -d

            # Cleanup redundant images
            docker image prune -f
            "
